# name: test1
# run-name: ${{ github.actor }} is creating on main ğŸš€
# on:
#   pull_request:
#     branches:
#       - 'main'
# jobs:
#   Explore-GitHub-Actions:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
#       - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#       - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#       - name: Check out repository code
#         uses: actions/checkout@v3
#       - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
#       - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
#       - name: List files in the repository
#         run: |
#           ls ${{ github.workspace }}
#       - run: echo "ğŸ This job's status is ${{ job.status }}."

# name: test2
# run-name: ${{ github.actor }} is creating a PR on main for some go app ğŸš€
# on:
#   pull_request:
#     branches:
#       - 'main'
#     paths:
#       - '**.go'

# jobs:
#   Explore-GitHub-Actions:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
#       - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#       - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#       - name: Check out repository code
#         uses: actions/checkout@v3
#       - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
#       - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
#       - name: List files in the repository
#         run: |
#           ls ${{ github.workspace }}
#       - run: echo "ğŸ This job's status is ${{ job.status }}."

name: test3
run-name: ${{ github.actor }} is creating a PR on main for some go app ğŸš€
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - '**.go'

jobs:
  IdentifyFolderChanges:
    # Required permissions
    permissions: read-all
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      api-server: ${{ steps.filter.outputs.api-server }}
      reddit-api-fetcher : ${{ steps.filter.outputs.reddit-api-fetcher }}
      reddit-api-processor: ${{ steps.filter.outputs.reddit-api-processor }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            api-server:
              - 'api-server/**'
            reddit-api-fetcher:
              - 'reddit-api/reddit-api-fetcher/**'
            reddit-api-processor:
              - 'reddit-api/reddit-api-processor/**'
  # JOB to lint and compile api-server code
  Api-Server:
    needs: IdentifyFolderChanges
    if: ${{ needs.IdentifyFolderChanges.outputs.api-server == 'true' }}
    uses: ./.github/workflows/go-app-pr-action.yml
    with:
      workdir: ./apiserver
  # JOB to lint and compile reddit-api-fetcher code
  Reddit-Api-Fetcher:
    needs:  IdentifyFolderChanges
    if: ${{ needs.IdentifyFolderChanges.outputs.reddit-api-fetcher == 'true' }}
    uses: ./.github/workflows/go-app-pr-action.yml
    with:
      workdir: ./reddit-api/reddit-api-fetcher
  # JOB to lint and compile reddit-api-processor code
  Reddit-Api-Processor:
    needs:  IdentifyFolderChanges
    if: ${{ needs.IdentifyFolderChanges.outputs.reddit-api-processor == 'true' }}
    uses: ./.github/workflows/go-app-pr-action.yml
    with:
      workdir: ./reddit-api/reddit-api-processor